"""fix_observation_unique_constraint

Revision ID: 231693562125
Revises: ba2ff30b4bb5
Create Date: 2026-02-18 19:35:04.071941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231693562125'
down_revision: Union[str, Sequence[str], None] = 'ba2ff30b4bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('file_object_metadata_uri_key'), 'file_object_metadata', type_='unique')
    op.drop_column('file_object_metadata', 'uri')
    op.drop_constraint(op.f('observation_record_id_key'), 'observation', type_='unique')
    op.create_unique_constraint('observation_unique_key', 'observation', ['record_id', 'record_type', 'parameter_id', 'unit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('observation_unique_key', 'observation', type_='unique')
    op.create_unique_constraint(op.f('observation_record_id_key'), 'observation', ['record_id'], postgresql_nulls_not_distinct=False)
    op.add_column('file_object_metadata', sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('file_object_metadata_uri_key'), 'file_object_metadata', ['uri'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
