"""fix_usda_schema_drift

Revision ID: ba2ff30b4bb5
Revises: a085cd4a462e
Create Date: 2026-02-18 16:55:01.292461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ba2ff30b4bb5'
down_revision: Union[str, Sequence[str], None] = 'a085cd4a462e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usda_commodity', sa.Column('api_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('usda_commodity', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('usda_commodity', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('usda_survey_record', sa.Column('begin_code', sa.Integer(), nullable=True))
    op.add_column('usda_survey_record', sa.Column('end_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usda_survey_record', 'end_code')
    op.drop_column('usda_survey_record', 'begin_code')
    op.drop_column('usda_commodity', 'updated_at')
    op.drop_column('usda_commodity', 'created_at')
    op.drop_column('usda_commodity', 'api_name')
    # ### end Alembic commands ###
